/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as HodRouteRouteImport } from './routes/hod/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as HodIndexRouteImport } from './routes/hod/index'
import { Route as UserRfqRouteImport } from './routes/user/rfq'
import { Route as UserDepartmentRouteImport } from './routes/user/department'
import { Route as UserCalendarRouteImport } from './routes/user/calendar'
import { Route as UserBudgetRouteImport } from './routes/user/budget'
import { Route as HodSettingsRouteImport } from './routes/hod/settings'
import { Route as HodReportsRouteImport } from './routes/hod/reports'
import { Route as HodLogsRouteImport } from './routes/hod/logs'
import { Route as HodCalendarRouteImport } from './routes/hod/calendar'
import { Route as UserHistoryRouteRouteImport } from './routes/user/history/route'
import { Route as UserBillingRouteRouteImport } from './routes/user/billing/route'
import { Route as HodBillingRouteRouteImport } from './routes/hod/billing/route'
import { Route as UserHistoryIndexRouteImport } from './routes/user/history/index'
import { Route as UserBillingIndexRouteImport } from './routes/user/billing/index'
import { Route as HodBillingIndexRouteImport } from './routes/hod/billing/index'
import { Route as UserHistoryBudgetIdRouteImport } from './routes/user/history/$budgetId'
import { Route as UserBillingBillingIdRouteImport } from './routes/user/billing/$billingId'
import { Route as HodBillingBillingIdRouteImport } from './routes/hod/billing/$billingId'
import { Route as AuthMicrosoftCallbackRouteImport } from './routes/auth/microsoft/callback'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const HodRouteRoute = HodRouteRouteImport.update({
  id: '/hod',
  path: '/hod',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRouteRoute,
} as any)
const HodIndexRoute = HodIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HodRouteRoute,
} as any)
const UserRfqRoute = UserRfqRouteImport.update({
  id: '/rfq',
  path: '/rfq',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserDepartmentRoute = UserDepartmentRouteImport.update({
  id: '/department',
  path: '/department',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserCalendarRoute = UserCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserBudgetRoute = UserBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => UserRouteRoute,
} as any)
const HodSettingsRoute = HodSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HodRouteRoute,
} as any)
const HodReportsRoute = HodReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => HodRouteRoute,
} as any)
const HodLogsRoute = HodLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => HodRouteRoute,
} as any)
const HodCalendarRoute = HodCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => HodRouteRoute,
} as any)
const UserHistoryRouteRoute = UserHistoryRouteRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserBillingRouteRoute = UserBillingRouteRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => UserRouteRoute,
} as any)
const HodBillingRouteRoute = HodBillingRouteRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => HodRouteRoute,
} as any)
const UserHistoryIndexRoute = UserHistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserHistoryRouteRoute,
} as any)
const UserBillingIndexRoute = UserBillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserBillingRouteRoute,
} as any)
const HodBillingIndexRoute = HodBillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HodBillingRouteRoute,
} as any)
const UserHistoryBudgetIdRoute = UserHistoryBudgetIdRouteImport.update({
  id: '/$budgetId',
  path: '/$budgetId',
  getParentRoute: () => UserHistoryRouteRoute,
} as any)
const UserBillingBillingIdRoute = UserBillingBillingIdRouteImport.update({
  id: '/$billingId',
  path: '/$billingId',
  getParentRoute: () => UserBillingRouteRoute,
} as any)
const HodBillingBillingIdRoute = HodBillingBillingIdRouteImport.update({
  id: '/$billingId',
  path: '/$billingId',
  getParentRoute: () => HodBillingRouteRoute,
} as any)
const AuthMicrosoftCallbackRoute = AuthMicrosoftCallbackRouteImport.update({
  id: '/auth/microsoft/callback',
  path: '/auth/microsoft/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hod': typeof HodRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/hod/billing': typeof HodBillingRouteRouteWithChildren
  '/user/billing': typeof UserBillingRouteRouteWithChildren
  '/user/history': typeof UserHistoryRouteRouteWithChildren
  '/hod/calendar': typeof HodCalendarRoute
  '/hod/logs': typeof HodLogsRoute
  '/hod/reports': typeof HodReportsRoute
  '/hod/settings': typeof HodSettingsRoute
  '/user/budget': typeof UserBudgetRoute
  '/user/calendar': typeof UserCalendarRoute
  '/user/department': typeof UserDepartmentRoute
  '/user/rfq': typeof UserRfqRoute
  '/hod/': typeof HodIndexRoute
  '/user/': typeof UserIndexRoute
  '/auth/microsoft/callback': typeof AuthMicrosoftCallbackRoute
  '/hod/billing/$billingId': typeof HodBillingBillingIdRoute
  '/user/billing/$billingId': typeof UserBillingBillingIdRoute
  '/user/history/$budgetId': typeof UserHistoryBudgetIdRoute
  '/hod/billing/': typeof HodBillingIndexRoute
  '/user/billing/': typeof UserBillingIndexRoute
  '/user/history/': typeof UserHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/hod/calendar': typeof HodCalendarRoute
  '/hod/logs': typeof HodLogsRoute
  '/hod/reports': typeof HodReportsRoute
  '/hod/settings': typeof HodSettingsRoute
  '/user/budget': typeof UserBudgetRoute
  '/user/calendar': typeof UserCalendarRoute
  '/user/department': typeof UserDepartmentRoute
  '/user/rfq': typeof UserRfqRoute
  '/hod': typeof HodIndexRoute
  '/user': typeof UserIndexRoute
  '/auth/microsoft/callback': typeof AuthMicrosoftCallbackRoute
  '/hod/billing/$billingId': typeof HodBillingBillingIdRoute
  '/user/billing/$billingId': typeof UserBillingBillingIdRoute
  '/user/history/$budgetId': typeof UserHistoryBudgetIdRoute
  '/hod/billing': typeof HodBillingIndexRoute
  '/user/billing': typeof UserBillingIndexRoute
  '/user/history': typeof UserHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hod': typeof HodRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/hod/billing': typeof HodBillingRouteRouteWithChildren
  '/user/billing': typeof UserBillingRouteRouteWithChildren
  '/user/history': typeof UserHistoryRouteRouteWithChildren
  '/hod/calendar': typeof HodCalendarRoute
  '/hod/logs': typeof HodLogsRoute
  '/hod/reports': typeof HodReportsRoute
  '/hod/settings': typeof HodSettingsRoute
  '/user/budget': typeof UserBudgetRoute
  '/user/calendar': typeof UserCalendarRoute
  '/user/department': typeof UserDepartmentRoute
  '/user/rfq': typeof UserRfqRoute
  '/hod/': typeof HodIndexRoute
  '/user/': typeof UserIndexRoute
  '/auth/microsoft/callback': typeof AuthMicrosoftCallbackRoute
  '/hod/billing/$billingId': typeof HodBillingBillingIdRoute
  '/user/billing/$billingId': typeof UserBillingBillingIdRoute
  '/user/history/$budgetId': typeof UserHistoryBudgetIdRoute
  '/hod/billing/': typeof HodBillingIndexRoute
  '/user/billing/': typeof UserBillingIndexRoute
  '/user/history/': typeof UserHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hod'
    | '/user'
    | '/login'
    | '/hod/billing'
    | '/user/billing'
    | '/user/history'
    | '/hod/calendar'
    | '/hod/logs'
    | '/hod/reports'
    | '/hod/settings'
    | '/user/budget'
    | '/user/calendar'
    | '/user/department'
    | '/user/rfq'
    | '/hod/'
    | '/user/'
    | '/auth/microsoft/callback'
    | '/hod/billing/$billingId'
    | '/user/billing/$billingId'
    | '/user/history/$budgetId'
    | '/hod/billing/'
    | '/user/billing/'
    | '/user/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/hod/calendar'
    | '/hod/logs'
    | '/hod/reports'
    | '/hod/settings'
    | '/user/budget'
    | '/user/calendar'
    | '/user/department'
    | '/user/rfq'
    | '/hod'
    | '/user'
    | '/auth/microsoft/callback'
    | '/hod/billing/$billingId'
    | '/user/billing/$billingId'
    | '/user/history/$budgetId'
    | '/hod/billing'
    | '/user/billing'
    | '/user/history'
  id:
    | '__root__'
    | '/'
    | '/hod'
    | '/user'
    | '/login'
    | '/hod/billing'
    | '/user/billing'
    | '/user/history'
    | '/hod/calendar'
    | '/hod/logs'
    | '/hod/reports'
    | '/hod/settings'
    | '/user/budget'
    | '/user/calendar'
    | '/user/department'
    | '/user/rfq'
    | '/hod/'
    | '/user/'
    | '/auth/microsoft/callback'
    | '/hod/billing/$billingId'
    | '/user/billing/$billingId'
    | '/user/history/$budgetId'
    | '/hod/billing/'
    | '/user/billing/'
    | '/user/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HodRouteRoute: typeof HodRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthMicrosoftCallbackRoute: typeof AuthMicrosoftCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod': {
      id: '/hod'
      path: '/hod'
      fullPath: '/hod'
      preLoaderRoute: typeof HodRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/hod/': {
      id: '/hod/'
      path: '/'
      fullPath: '/hod/'
      preLoaderRoute: typeof HodIndexRouteImport
      parentRoute: typeof HodRouteRoute
    }
    '/user/rfq': {
      id: '/user/rfq'
      path: '/rfq'
      fullPath: '/user/rfq'
      preLoaderRoute: typeof UserRfqRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/department': {
      id: '/user/department'
      path: '/department'
      fullPath: '/user/department'
      preLoaderRoute: typeof UserDepartmentRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/calendar': {
      id: '/user/calendar'
      path: '/calendar'
      fullPath: '/user/calendar'
      preLoaderRoute: typeof UserCalendarRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/budget': {
      id: '/user/budget'
      path: '/budget'
      fullPath: '/user/budget'
      preLoaderRoute: typeof UserBudgetRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/hod/settings': {
      id: '/hod/settings'
      path: '/settings'
      fullPath: '/hod/settings'
      preLoaderRoute: typeof HodSettingsRouteImport
      parentRoute: typeof HodRouteRoute
    }
    '/hod/reports': {
      id: '/hod/reports'
      path: '/reports'
      fullPath: '/hod/reports'
      preLoaderRoute: typeof HodReportsRouteImport
      parentRoute: typeof HodRouteRoute
    }
    '/hod/logs': {
      id: '/hod/logs'
      path: '/logs'
      fullPath: '/hod/logs'
      preLoaderRoute: typeof HodLogsRouteImport
      parentRoute: typeof HodRouteRoute
    }
    '/hod/calendar': {
      id: '/hod/calendar'
      path: '/calendar'
      fullPath: '/hod/calendar'
      preLoaderRoute: typeof HodCalendarRouteImport
      parentRoute: typeof HodRouteRoute
    }
    '/user/history': {
      id: '/user/history'
      path: '/history'
      fullPath: '/user/history'
      preLoaderRoute: typeof UserHistoryRouteRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/billing': {
      id: '/user/billing'
      path: '/billing'
      fullPath: '/user/billing'
      preLoaderRoute: typeof UserBillingRouteRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/hod/billing': {
      id: '/hod/billing'
      path: '/billing'
      fullPath: '/hod/billing'
      preLoaderRoute: typeof HodBillingRouteRouteImport
      parentRoute: typeof HodRouteRoute
    }
    '/user/history/': {
      id: '/user/history/'
      path: '/'
      fullPath: '/user/history/'
      preLoaderRoute: typeof UserHistoryIndexRouteImport
      parentRoute: typeof UserHistoryRouteRoute
    }
    '/user/billing/': {
      id: '/user/billing/'
      path: '/'
      fullPath: '/user/billing/'
      preLoaderRoute: typeof UserBillingIndexRouteImport
      parentRoute: typeof UserBillingRouteRoute
    }
    '/hod/billing/': {
      id: '/hod/billing/'
      path: '/'
      fullPath: '/hod/billing/'
      preLoaderRoute: typeof HodBillingIndexRouteImport
      parentRoute: typeof HodBillingRouteRoute
    }
    '/user/history/$budgetId': {
      id: '/user/history/$budgetId'
      path: '/$budgetId'
      fullPath: '/user/history/$budgetId'
      preLoaderRoute: typeof UserHistoryBudgetIdRouteImport
      parentRoute: typeof UserHistoryRouteRoute
    }
    '/user/billing/$billingId': {
      id: '/user/billing/$billingId'
      path: '/$billingId'
      fullPath: '/user/billing/$billingId'
      preLoaderRoute: typeof UserBillingBillingIdRouteImport
      parentRoute: typeof UserBillingRouteRoute
    }
    '/hod/billing/$billingId': {
      id: '/hod/billing/$billingId'
      path: '/$billingId'
      fullPath: '/hod/billing/$billingId'
      preLoaderRoute: typeof HodBillingBillingIdRouteImport
      parentRoute: typeof HodBillingRouteRoute
    }
    '/auth/microsoft/callback': {
      id: '/auth/microsoft/callback'
      path: '/auth/microsoft/callback'
      fullPath: '/auth/microsoft/callback'
      preLoaderRoute: typeof AuthMicrosoftCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HodBillingRouteRouteChildren {
  HodBillingBillingIdRoute: typeof HodBillingBillingIdRoute
  HodBillingIndexRoute: typeof HodBillingIndexRoute
}

const HodBillingRouteRouteChildren: HodBillingRouteRouteChildren = {
  HodBillingBillingIdRoute: HodBillingBillingIdRoute,
  HodBillingIndexRoute: HodBillingIndexRoute,
}

const HodBillingRouteRouteWithChildren = HodBillingRouteRoute._addFileChildren(
  HodBillingRouteRouteChildren,
)

interface HodRouteRouteChildren {
  HodBillingRouteRoute: typeof HodBillingRouteRouteWithChildren
  HodCalendarRoute: typeof HodCalendarRoute
  HodLogsRoute: typeof HodLogsRoute
  HodReportsRoute: typeof HodReportsRoute
  HodSettingsRoute: typeof HodSettingsRoute
  HodIndexRoute: typeof HodIndexRoute
}

const HodRouteRouteChildren: HodRouteRouteChildren = {
  HodBillingRouteRoute: HodBillingRouteRouteWithChildren,
  HodCalendarRoute: HodCalendarRoute,
  HodLogsRoute: HodLogsRoute,
  HodReportsRoute: HodReportsRoute,
  HodSettingsRoute: HodSettingsRoute,
  HodIndexRoute: HodIndexRoute,
}

const HodRouteRouteWithChildren = HodRouteRoute._addFileChildren(
  HodRouteRouteChildren,
)

interface UserBillingRouteRouteChildren {
  UserBillingBillingIdRoute: typeof UserBillingBillingIdRoute
  UserBillingIndexRoute: typeof UserBillingIndexRoute
}

const UserBillingRouteRouteChildren: UserBillingRouteRouteChildren = {
  UserBillingBillingIdRoute: UserBillingBillingIdRoute,
  UserBillingIndexRoute: UserBillingIndexRoute,
}

const UserBillingRouteRouteWithChildren =
  UserBillingRouteRoute._addFileChildren(UserBillingRouteRouteChildren)

interface UserHistoryRouteRouteChildren {
  UserHistoryBudgetIdRoute: typeof UserHistoryBudgetIdRoute
  UserHistoryIndexRoute: typeof UserHistoryIndexRoute
}

const UserHistoryRouteRouteChildren: UserHistoryRouteRouteChildren = {
  UserHistoryBudgetIdRoute: UserHistoryBudgetIdRoute,
  UserHistoryIndexRoute: UserHistoryIndexRoute,
}

const UserHistoryRouteRouteWithChildren =
  UserHistoryRouteRoute._addFileChildren(UserHistoryRouteRouteChildren)

interface UserRouteRouteChildren {
  UserBillingRouteRoute: typeof UserBillingRouteRouteWithChildren
  UserHistoryRouteRoute: typeof UserHistoryRouteRouteWithChildren
  UserBudgetRoute: typeof UserBudgetRoute
  UserCalendarRoute: typeof UserCalendarRoute
  UserDepartmentRoute: typeof UserDepartmentRoute
  UserRfqRoute: typeof UserRfqRoute
  UserIndexRoute: typeof UserIndexRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserBillingRouteRoute: UserBillingRouteRouteWithChildren,
  UserHistoryRouteRoute: UserHistoryRouteRouteWithChildren,
  UserBudgetRoute: UserBudgetRoute,
  UserCalendarRoute: UserCalendarRoute,
  UserDepartmentRoute: UserDepartmentRoute,
  UserRfqRoute: UserRfqRoute,
  UserIndexRoute: UserIndexRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HodRouteRoute: HodRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthMicrosoftCallbackRoute: AuthMicrosoftCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
